"""Render `GRAPH_REPORT.md` from the graph + analysis outputs."""

from __future__ import annotations

from collections import Counter
from pathlib import Path

import networkx as nx


def generate(
    G: nx.DiGraph,
    communities: dict[int, list[str]],
    analysis: dict,
) -> str:
    """Build a human + agent-friendly summary in Markdown."""
    lines: list[str] = ["# Pluto Graph Report", ""]
    lines.append(f"- Nodes: **{G.number_of_nodes()}**")
    lines.append(f"- Edges: **{G.number_of_edges()}**")
    lines.append(f"- Communities: **{len(communities)}**")
    lines.append("")

    type_counts = Counter(attrs.get("type", "?") for _, attrs in G.nodes(data=True))
    if type_counts:
        lines.append("## Node breakdown by type")
        lines.append("")
        lines.append("| Type | Count |")
        lines.append("|---|---|")
        for t, c in sorted(type_counts.items(), key=lambda p: -p[1]):
            lines.append(f"| {t} | {c} |")
        lines.append("")

    conf_counts = Counter(attrs.get("confidence", "?") for _, _, attrs in G.edges(data=True))
    if conf_counts:
        lines.append("## Edge confidence")
        lines.append("")
        for c, n in sorted(conf_counts.items(), key=lambda p: -p[1]):
            lines.append(f"- **{c}**: {n}")
        lines.append("")

    gods = analysis.get("god_nodes", [])
    if gods:
        lines.append("## God nodes (top by degree)")
        lines.append("")
        lines.append("| Degree | Type | Name | Source |")
        lines.append("|---|---|---|---|")
        for g in gods:
            src = g.get("src") or "-"
            lines.append(f"| {g['degree']} | {g['type']} | `{g['name']}` | `{src}` |")
        lines.append("")

    if communities:
        lines.append("## Communities")
        lines.append("")
        sized = sorted(communities.items(), key=lambda p: -len(p[1]))
        for cid, members in sized[:20]:
            sample = [G.nodes[m].get("name", m) for m in members[:5] if G.has_node(m)]
            lines.append(f"- **C{cid}** ({len(members)} nodes): " + ", ".join(f"`{s}`" for s in sample))
        lines.append("")

    surprises = analysis.get("surprises", [])
    if surprises:
        lines.append("## Cross-community surprises")
        lines.append("")
        lines.append("Edges that jump between communities — likely architectural seams.")
        lines.append("")
        for s in surprises:
            lines.append(
                f"- `{s['source']}` → `{s['target']}` "
                f"(C{s['source_community']} → C{s['target_community']}, type={s['type']})"
            )
        lines.append("")

    questions = analysis.get("suggested_questions", [])
    if questions:
        lines.append("## Suggested first questions")
        lines.append("")
        for q in questions:
            lines.append(f"- {q}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("Generated by [pluto](https://github.com/pluto-graph/pluto).")
    return "\n".join(lines)


def write(path: Path, content: str) -> None:
    """Persist `content` to `path`, creating parents as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
